### ISSUE TITLE
Project update?

### ISSUE THREAD

**Issue by ghost** [laanwj/munt#2]
Thanks for the plugin!
Do you plan to rebase your work against more recent munt? For e.g. 2.3.0
Also could you post your changes upstream?

**Comment by laanwj** [comment]
Hey! Thanks for the interest.

> Do you plan to rebase your work against more recent munt? For e.g. 2.3.0

This definitely needed, hope to get around to it at some point—but I'm afraid I don't currently have time to do this, unfortunately, haven't been able to do much in regard to music stuff for long :cry:

**Comment by nyanpasu64** [comment]
I've tried to squash-merge this branch on master, haven't pushed my branch yet.

## Merge conflicts

- top level cmakelists changed

lv2 changes to munt core:
- writeMemory (for lv2 plugin savestate restoration)
- softReset (for void MuntPlugin::deactivate())

## Build issues

- `MT32EMU_MEMADDR` is missing by default (`#include "../../mt32emu/src/Structures.h"` works but is ugly)
- some types are now incomplete
- some variables are made private.

upstream changes to munt core:
```
commit cbc7efbb2f68dd2d3be7122b93a522fdbf47dd40
Author: sergm <sergm@bigmir.net>
Date:   Sat Dec 20 20:54:09 2014 +0200

    - Started major API refactoring: most internals which cannot (shouldn't) be accessed by clients are now hidden, also this reduces namespace pollution
    - Synth::getPartial() turned to Synth::getPartialStates() making direct access to Partial unnecessary
```

```
commit 8c7a23f6146a5d692ab8de97f79d6c767d521d57
Author: sergm <sergm@bigmir.net>
Date:   Sat Dec 20 21:59:09 2014 +0200

    - Synth::getPart() made private
    - Introduced getPartStates() and getPlayingNotes() in Synth to facilitate visualisation of synth state while avoiding access to internal classes
```

To fix the build, I stubbed out the "active or non-releasing parts (aka notes)" feature to always return 0.

Conflicting headers caused by
```
commit 37a609a9371077c61f26761dc8c0ee5f8233e529
Author: sergm <sergm@bigmir.net>
Date:   Tue Feb 7 21:10:39 2017 +0200

    - Moved sample rate conversion feature from mt32emu-qt to the libmt32emu, so it can be easily used in other applications
```

Also, according to kdevelop, `#include <mt32emu/mt32emu.h>` is pulling from `/usr/include/mt32emu/mt32emu.h` which is missing writeMemory and softReset.

**Comment by gnidorah** [comment]
@jimbo1qaz Another more flexible approach is to add sysex banks loading feature and JACK support to Munt. Then you just use Munt as standalone synth and bind it with other JACK applications

**Comment by nyanpasu64** [comment]
https://github.com/jimbo1qaz/munt/tree/master-lv2

It builds, I haven't checked if it works. I think I'll be stopping work here.
